In [1]:
# model setup

import numpy as np

def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))

def sigmoid_derivative(A):
    return A * (1 - A)

In [2]:
# initialize weights

def init_zero():
    W1 = np.zeros((2, 2))
    b1 = np.zeros((2, 1))
    W2 = np.zeros((1, 2))
    b2 = np.zeros((1, 1))
    return W1, b1, W2, b2


def init_random():
    np.random.seed(42)
    W1 = np.random.randn(2, 2) * 0.1
    b1 = np.zeros((2, 1))
    W2 = np.random.randn(1, 2) * 0.1
    b2 = np.zeros((1, 1))
    return W1, b1, W2, b2

In [3]:
# forward + backward

def forward(X, W1, b1, W2, b2):
    Z1 = W1 @ X + b1
    A1 = sigmoid(Z1)

    Z2 = W2 @ A1 + b2
    A2 = sigmoid(Z2)

    return Z1, A1, Z2, A2


def backward(X, Y, Z1, A1, Z2, A2, W2):
    m = X.shape[1]

    dZ2 = A2 - Y
    dW2 = (1/m) * dZ2 @ A1.T
    db2 = (1/m) * np.sum(dZ2, axis=1, keepdims=True)

    dA1 = W2.T @ dZ2
    dZ1 = dA1 * sigmoid_derivative(A1)
    dW1 = (1/m) * dZ1 @ X.T
    db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)

    return dW1, db1, dW2, db2

In [4]:
# training function

def train(init_fn, epochs=1000, lr=0.1):
    X = np.array([[0,0,1,1],
                  [0,1,0,1]])
    Y = np.array([[0,1,1,0]])

    W1, b1, W2, b2 = init_fn()

    for i in range(epochs):
        Z1, A1, Z2, A2 = forward(X, W1, b1, W2, b2)

        loss = -np.mean(Y*np.log(A2+1e-8) + (1-Y)*np.log(1-A2+1e-8))

        dW1, db1, dW2, db2 = backward(X, Y, Z1, A1, Z2, A2, W2)

        W1 -= lr * dW1
        b1 -= lr * db1
        W2 -= lr * dW2
        b2 -= lr * db2

        if i % 200 == 0:
            print(f"Epoch {i}, Loss: {loss:.4f}")

    return W1, b1, W2, b2

In [5]:
print("Training with ZERO initialization")
train(init_zero)

Training with ZERO initialization
Epoch 0, Loss: 0.6931
Epoch 200, Loss: 0.6931
Epoch 400, Loss: 0.6931
Epoch 600, Loss: 0.6931
Epoch 800, Loss: 0.6931


(array([[0., 0.],
        [0., 0.]]),
 array([[0.],
        [0.]]),
 array([[0., 0.]]),
 array([[0.]]))

In [6]:
print("Training with RANDOM initialization")
train(init_random)

Training with RANDOM initialization
Epoch 0, Loss: 0.6932
Epoch 200, Loss: 0.6931
Epoch 400, Loss: 0.6931
Epoch 600, Loss: 0.6931
Epoch 800, Loss: 0.6931


(array([[ 0.04963811, -0.01388937],
        [ 0.06424033,  0.15198779]]),
 array([[-5.74957041e-05],
        [-2.93657841e-04]]),
 array([[-0.0157672 , -0.01361905]]),
 array([[0.01515413]]))